### ISSUE TITLE
class attributes of MyNeurons in reverse order to convention

### ISSUE THREAD

**Issue by zhihaozheng** [jefferis/AnalysisSuite#7]
Just a minor one but since I run into it I want to note it here.

`class(MyNeurons)` returns "list" "neuronlist"

The convention should be "neuronlist" "list" (from most to least specific). Otherwise, for example, it will print an error with `as.data.frame(MyNeurons)` (also `plot3d(MyNeurons)`) since it was trying to do `c.neuronlist` with the misplaced class attributes.

**Comment by jefferis** [comment]
Thanks, @zhihaozheng. Quite right! We don't really use this dataset anymore - it is here for historical purposes. Also you may not have noticed, but the recommended may to run this codebase now is to use the [nat.as](https://github.com/jefferis/nat.as) package.

**Comment by zhihaozheng** [comment]
Oh, yes I didn't notice. Thanks for telling me!
